# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=25)),
                ('exposure', models.ManyToManyField(to='tracker.Exposure')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Garden')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('area', models.ManyToManyField(to='tracker.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('sci_name', models.CharField(max_length=70)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('moisture', models.CharField(max_length=25)),
                ('bloom_season', models.CharField(max_length=25)),
                ('food', models.BooleanField()),
                ('exposure', models.ManyToManyField(to='tracker.Exposure')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.ManyToManyField(to='tracker.Location')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Log')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Planting')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='planting',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Status'),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.ManyToManyField(to='tracker.Soil'),
        ),
    ]
