# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170519_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='planting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
