# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170519_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='garden',
        ),
    ]
